---
#-----------------------------------------------------------------------------------------------------------
# Playbook that installs the Codekvast Server application, which is an executable Spring Boot jar
#-----------------------------------------------------------------------------------------------------------
- name: Codekvast Server Application
  hosts: tag_role_backend
  user: ubuntu
  become: yes
  serial: 1

  vars_files:
  - vars/secrets.yml
  - vars/common.yml

  vars:
    customer: "{{ hostvars[inventory_hostname]['ec2_tag_Customer'] }}"
    env: "{{ hostvars[inventory_hostname]['ec2_tag_Env'] }}"
    database_group_name: "tag_Name_Codekvast_{{ customer }}_{{ env }}_database"

    codekvast_queue_path: /var/codekvast/queue
    codekvast_queue_pollIntervalSeconds: 30
    codekvast_webapp_jwtExpirationHours: 168
    codekvast_herokuCodekvastUrl: https://{{ codekvast_server_name }}
    codekvastVersion: "{{ lookup('ini', 'codekvastVersion type=properties file=../../gradle.properties') }}"

  tasks:
  - name: Lookup the private DNS name for the database server
    set_fact: database_dns_names="{{ groups[database_group_name]|map('extract', hostvars, 'ec2_private_dns_name')|list }}"

  - name: Setting timezone to UTC
    timezone: name=UTC

  - name: Install OpenJDK 8
    package: name=openjdk-8-jdk-headless state=installed
    notify: restart codekvast

  - name: Create codekvast group
    group: name=codekvast state=present

  - name: Create codekvast user
    user: name=codekvast group=codekvast state=present home=/opt/codekvast

  - name: Create directories
    file: path={{ item }} state=directory owner=codekvast group=codekvast
    with_items:
    - "{{ codekvast_queue_path }}"
    - /var/log/codekvast

  - name: Install codekvast executable jar
    copy:
      src: ../../product/dashboard/build/libs/codekvast-dashboard-{{ codekvastVersion }}-all.jar
      dest: /opt/codekvast/codekvast-dashboard-{{ codekvastVersion }}-all.jar
      owner: codekvast
      group: codekvast
      mode: 0700
    notify: restart codekvast

  - name: Install Codekvast configuration file
    template: src=codekvast/application.properties dest=/opt/codekvast/application.properties owner=codekvast group=codekvast
    notify: restart codekvast

  - name: Install /etc/systemd/system/codekvast.service
    template: src=codekvast/codekvast.service dest=/etc/systemd/system/codekvast.service owner=root group=root
    notify:
    - systemctl daemon-reload
    - restart codekvast

  - name: Enable codekvast service
    service: name=codekvast enabled=yes

  - name: Start codekvast service
    service: name=codekvast state=started

  - meta: flush_handlers

  - name: Wait until service has started
    wait_for: port=8080 state=started timeout=30

#  - name: Remove cruft
#    file: path={{ item }} state=absent
#    with_items:
#    - /var/log/codekvast.log

  handlers:
  - name: systemctl daemon-reload
    shell: systemctl daemon-reload

  - name: restart codekvast
    service: name=codekvast state=restarted
