#-------------------------------------------------------------------------------------------------------------------------------------------
# This file contains all properties that are NOT injected by Gradle. These go into application.properties, since Gradle's expand()
# does not play well with YAML.
#
# Spring Boot reads both application.properties and application.yml.
#-------------------------------------------------------------------------------------------------------------------------------------------

codekvast:
    cipherSecret: someCipherSecret
    dashboardBaseUrl: http://localhost:8081
    dashboardJwtExpirationHours: 168
    dashboardJwtSecret: secret
    dnsCname: localhost
    herokuOAuthBaseUrl: https://id.heroku.com
    herokuApiBaseUrl: https://api.heroku.com
    herokuApiPassword: herokuApiPassword
    herokuApiSsoSalt: herokuApiSsoSalt
    herokuCodekvastUrl: http://localhost:8080
    herokuOAuthClientId: herokuOAuthClientId
    herokuOAuthClientSecret: herokuOAuthClientSecret
    slackWebHookToken:
    slackWebHookUrl: https://hooks.slack.com/services

logging:
    file: build/log/login.log
    level:
        io.codekvast: DEBUG

management:
    endpoints:
        jmx.domain: CodekvastLogin
        web:
            base-path: /management
            exposure.include: '*'
    server:
        port: 9080
        servlet.context-path: /
    metrics:
        web.server.auto-time-requests: true
        export.cloudwatch:
            enabled: false
            step: PT10S
            readTimeout: PT30S
            batchSize: 20000
cloudwatch:
    namespace: xxx

server:
    port: 8080
    servlet:
        context-path: /
        session:
            cookie:
                max-age: 10m
            persistent: false
    undertow:
        accesslog:
            dir: build/log
            enabled: true
            pattern: combined
            prefix: access.
    use-forward-headers: true

spring:
    application.name: Codekvast Login
    boot.admin.client:
        url: http://localhost:8082
        auto-registration: true
        auto-deregistration: false
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
        password: codekvast
        url: jdbc:mariadb://localhost/codekvast
        username: codekvast
    flyway:
        table: schema_version
        validate-on-migrate: false
    groovy.template:
        suffix: .tpl
        configuration:
            auto-new-line: true
            auto-indent: true
    http.converters.preferred-json-mapper: gson
    output.ansi.enabled: detect
