---
- name: Lookup the private DNS name for the database server
  set_fact: database_dns_names="{{ groups[database_group_name]|map('extract', hostvars, 'ec2_private_dns_name')|list }}"

- name: Setting timezone to UTC
  timezone: name=UTC

- name: Install OpenJDK 8
  package: name=openjdk-8-jdk-headless state=installed
  notify: "restart codekvast service"

- name: Create codekvast group
  group: name=codekvast state=present

- name: Create codekvast user
  user: name=codekvast group=codekvast state=present home=/opt/codekvast

- name: Create directories
  file: path={{ item }} state=directory owner=codekvast group=codekvast
  with_items:
  - "/opt/codekvast/{{ service_name }}"
  - /var/log/codekvast

- name: "Install codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar"
  copy:
    src: ../../product/{{ service_name }}/build/libs/codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar
    dest: "/opt/codekvast/{{ service_name }}/codekvast-{{ service_name }}-{{ codekvastVersion }}-all.jar"
    owner: codekvast
    group: codekvast
    mode: 0700
  notify: "restart codekvast service"

- name: "Configure Codekvast {{ service_name | capitalize }}"
  template:
    src: "codekvast/{{ service_name }}/application.properties"
    dest: "/opt/codekvast/{{ service_name }}/application.properties"
    owner: codekvast
    group: codekvast
  notify: "restart codekvast service"

- name: "Install /etc/systemd/system/codekvast-{{ service_name }}.service"
  template:
    src: "systemd.service"
    dest: "/etc/systemd/system/codekvast-{{ service_name }}.service"
    owner: root
    group: root
  notify:
  - systemctl daemon-reload
  - "restart codekvast service"

- name: "Enable codekvast-{{ service_name }}"
  service:
    name: "codekvast-{{ service_name }}"
    enabled: yes

- name: "Start codekvast-{{ service_name }}"
  service:
    name: "codekvast-{{ service_name }}"
    state: started

- meta: flush_handlers

- name: "Wait until codekvast-{{ service_name }} has started"
  wait_for:
    port: "{{ service_port }}"
    state: started
    timeout: 30
