---
- hosts: all
  connection: local
  become: yes

  vars_files:
  - vars/secrets.yml

  handlers:
  - include: handlers/main.yml

  roles:
  - {role: franklinkim.docker, tags: [docker, docker-engine], distribution_release: zesty}
  
  post_tasks:
  - {include: tasks/tools.yml, tags: tools}
  - {include: tasks/docker.yml, tags: docker}
  - {include: tasks/aws-cli.yml, tags: aws}
  - {include: tasks/google-chrome.yml, tags: chrome}
