# Common variables used by more than one playbook

aws_region: eu-central-1

aws_stacks:
- {customer: default, env: prod,    cidr_base: "10.0", state: present, app_cnames: ['api', 'login', 'dashboard'], db_cname: 'db', backend_count: 2}
- {customer: default, env: staging, cidr_base: "10.1", state: present, app_cnames: ['api-staging', 'login-staging', 'dashboard-staging'], db_cname: 'db-staging', backend_count: 2}

ports:
  dashboard:
    service: 8081
    management: 9081
  login:
    service: 8080
    management: 9080

settings:
  session:
    cookie:
      name: JSESSIONID
  prod:
    hsts:
      max_age_seconds: 2592000 # 30 days
  staging:
    hsts:
      max_age_seconds: 3600 # one hour
